name: CI Pipeline for FE

on:
  push:
    branches:
      - develop

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install package
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Unit test
        run: "npm run test:ci"
